export default function Head() {
  const { user } = useContext();
  return (
    <>
      <title>{user} Settings</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
